# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: Md Sulaiman
has_binder: false
has_settings: true
kind: frontend
labextension_name: jupyterlab-khulnasoft
project_short_description: A JupyterLab extension to get AI code completion with khulnasoft
python_name: jupyterlab_khulnasoft
repository: https://github.com/khulnasoft/jupyterlab-khulnasoft
test: false

